### ISSUE TITLE
Questions about Bag Augmentation in the paper

### ISSUE THREAD

**Issue by invisprints** [Dootmaan/ICMIL#1]
First of all, thank you for your hard work. I would like to ask if the implementation of bag augmentation in the paper is reflected in the code? I have looked at your two branches in the repository and have not found any relevant clues.

**Comment by Dootmaan** [comment]
> First of all, thank you for your hard work. I would like to ask if the implementation of bag augmentation in the paper is reflected in the code? I have looked at your two branches in the repository and have not found any relevant clues.

Hi @invisprints and thank you for pointing this out.  The bag augmentation should have been in the confidence_based branch but we forgot to copy this part of code to the step1_xxx.py files before. We have updated this repo and now you should find them in the step1_xxx.py files. We also would like to thank the authors of PseMix for providing open implementations of different augmentation methods as our code is built based on their contributions.
